spring.application.name=quick-cache
spring.profiles.active=local_cache

#com.sartaj.quick-cache.multiCache.user.maxCapacity=200
#com.sartaj.quick-cache.multiCache.admin.maxCapacity=200

com.sartaj.quick-cache.default.maxCapacity=20
